alias cls="clear"
alias home="cd /mnt/c/Users/jonny"
alias pest="./vendor/bin/pest"
alias php-server="php -S localhost:8000"
alias art="php artisan"
alias python="python3"
alias pip="pip3"
alias composer="php /usr/local/bin/composer"
